### ISSUE TITLE
change age not precisely

### ISSUE THREAD

**Issue by shartoo** [pbaylies/stylegan-encoder#10]
Hi,thank you for sharing your awesome repo,thus i could make lots of fun.While playing with this repo i found it's not precisely when generating older faces,for example.

Here is the original image
![00559](https://user-images.githubusercontent.com/5716282/61846337-55ac4400-aed9-11e9-8349-bd64e833bbec.png)

and the geneated aged old face with age coeff=-2.0 is

![00559-1](https://user-images.githubusercontent.com/5716282/61846421-9a37df80-aed9-11e9-91c6-867e756b524c.jpg)

**Comment by pbaylies** [comment]
I mean, that looks a bit older to me. All the experiments with age vectors and whatnot come from Puzer's code, and he also has a notebook (still in this repo) explaining how it works, as well as some other directions for refinement. Good luck!
