### ISSUE TITLE
feature axis corelated with each other

### ISSUE THREAD

**Issue by shartoo** [pbaylies/stylegan-encoder#16]
I once edited image on age or gender direction and bad result return.For example

+ i want to make a female be older but increase the age direction coef may leading to her gender be male like

+ if i made a male older ,this will lead a glass appear on his face

Obviously, feature direction are corelated with each other.We could borrow idea from tl-gan such as feature disentangle.There are two scripts there which i thought very helpful ,`feature_axis.py`  and `script_label_regression.py` .

**Comment by pbaylies** [comment]
Thanks @shartoo I'll take a look at this! I've just been focused on encoding in this repo until now, but I'm interested in feature directions as well. All the pre-trained feature vectors are from Puzer's original code.
