### ISSUE TITLE
Finding latent representation in other domain

### ISSUE THREAD

**Issue by JanBoskamp** [pbaylies/stylegan-encoder#17]
First of all, thanks Pbaylies for sharing this great repo! Hopefully you can help me with the following. 

How can I find a latent representation of myself, in an portrait-art stylegan model? Right now, I can find a good latent representation of myself, but the generated image is not in portrait art style. This generated image is in the style of the original FFHQ stylegan model, just similar as the image of myself. How can I achieve what e.g. aiportraits.com has, showing the most similar representation of a person in a portrait-art stylegan model? I have tried to play with parameters and cross-over latent codes, but still without succes.

**Comment by pbaylies** [comment]
Hi @JanBoskamp -- you'd want to use a StyleGAN model that's been trained on portraits, take a look at [the notebook in this repo](https://github.com/ak9250/stylegan-art), by @ak9250

For the encoder parameters, you'll need to specify the model_url and the model_res (512 in this case) as well. Here's [an example](https://twitter.com/pbaylies/status/1130872216168673287) of what you can expect.

**Comment by JanBoskamp** [comment]
Hi @pbaylies , thanks for your answer, but let me clarify what I mean. With the Stylegan model I have trained, I can create portrait art (similar to @ak9250) and that looks like real art. Very cool. But when I try to find a latent representation in this art domain for an FFHQ image, or an image of myself, the generated image doesn't look like art. Although I am only using the art-stylegan model and not the well-known FFHQ stylegan model to find the representations.

I have attached two example art-stylegan results, and two found latent representations and their images. Any idea how I can force the encoding process to stay more in the art domain? In other words, how can I generate art-stylegan images, with similar facial features as the images of faces I use as input. The example of Elon Musk is the goal I try to achieve with my own model.

Thanks again!

![image](https://user-images.githubusercontent.com/18460631/62656657-fd5b5480-b964-11e9-8274-6a79363ce29a.png)
![image](https://user-images.githubusercontent.com/18460631/62656675-08ae8000-b965-11e9-951d-98784de19d31.png)
![image](https://user-images.githubusercontent.com/18460631/62656696-0ea46100-b965-11e9-9d94-8a2ad9eeec67.png)

**Comment by pbaylies** [comment]
Oh hey, nice model, I'd love to try that out! What you should try is raising the L1 penalty (the --use_l1_penalty flag), that will pull it more towards the center of the distribution, i.e., the art domain. Try raising it to 2 or 4, probably 20 would be too high, but somewhere in there.

**Comment by portnoyv** [comment]
Looks great, Can you share the pre trained wiki-art network? Also, did you train resnet/effnet on wikiart data?

**Comment by portnoyv** [comment]
@JanBoskamp did you succeed?
