### ISSUE TITLE
image alignment corrupts 32bit images

### ISSUE THREAD

**Issue by eyaler** [pbaylies/stylegan-encoder#18]
when a padding is needed, the code in face_alignment will corrupt images with an alpha channel. fixed by:

`        img = PIL.Image.open(src_file).convert('RGBA').convert('RGB')
`

**Comment by pbaylies** [comment]
@eyaler Thanks; I've seen this happen before. Feel free to submit a patch, or point me in the right direction, otherwise, I might track it down eventually...

**Comment by eyaler** [comment]
thanks. its just the above. in face_alignment.py replace:
` img = PIL.Image.open(src_file)`
with:
` img = PIL.Image.open(src_file).convert('RGBA').convert('RGB')`
this should also take care of your 'alpha' option
