### ISSUE TITLE
dlatent_avg explain

### ISSUE THREAD

**Issue by khiemkhanh98** [pbaylies/stylegan-encoder#23]
Hi pbaylies,

just wanna say thank u for your wonderful repos. However, as i can see from the NVlabs original readme, they said that the truncation trick will be disables when we use the subnetwork of the G and we would have to do it manually. Since your code is using the dlatent and only make use of the synthesis network , i think that the dlatent_avg part is missing the truncation trick part.
Please correct me if i'm wrong

**Comment by pbaylies** [comment]
Hi @khiemkhanh98 you need the dlatent average to perform the truncation trick properly in latents, you can see that from their example code as well. I'm glad you like the repo!
