### ISSUE TITLE
Confusing description of stochastic clipping in the CLI

### ISSUE THREAD

**Issue by jankrepl** [pbaylies/stylegan-encoder#25]
Hey!
First of all thank you for all the brilliant work on this project!
 
One thing that confused me was the description of the `clipping_threshold` in your `encode_images.py` CLI

> Stochastic clipping of gradient values outside of this threshold

However this technique does not clip gradients - it clips the values of the optimized variable.

**Comment by pbaylies** [comment]
Good point @jankrepl -- that should be dlatent values here, not gradient values! If you've looked at the code or you know the technique, then you know what this does, but yes, if a value goes out of range (by default from [-2..2]), it gets assigned a random value within the valid range.

**Comment by shyanguan** [comment]
The clip operation inspired me a lot! Thanks all!
