### ISSUE TITLE
Question about non human face data

### ISSUE THREAD

**Issue by hbarovertwo** [pbaylies/stylegan-encoder#27]
Hi @pbaylies 

I know that the faces dataset model is the highest quality among the several models that exist, but I was interested in the cars model. It generates good images, and I was hoping to encode some existing images into the car model's latent space and interpolate between them. However the results, using the existing pre-trained cars model and training resnet a bit did not do well at embedding images.
Any advice?
Thanks!
![acura1](https://user-images.githubusercontent.com/29473325/67173733-9529e580-f38d-11e9-8310-e13790ab9e2b.png)

**Comment by pbaylies** [comment]
Hi @hbarovertwo 

I haven't tried this personally with cars, but the ResNet can take a while to train well. As for encoding, your results may vary, especially if the images you are trying to encode aren't similar to the training data. Good luck!

**Comment by cssddnnc9527** [comment]
> Hi @pbaylies
> 
> I know that the faces dataset model is the highest quality among the several models that exist, but I was interested in the cars model. It generates good images, and I was hoping to encode some existing images into the car model's latent space and interpolate between them. However the results, using the existing pre-trained cars model and training resnet a bit did not do well at embedding images. Any advice? Thanks! ![acura1](https://user-images.githubusercontent.com/29473325/67173733-9529e580-f38d-11e9-8310-e13790ab9e2b.png)

Hi @hbarovertwo 

Have you resolve your work to generate high quality car image? 
Currently I'm also trying to encoder a car image, not very clear as follows:
![baoma](https://user-images.githubusercontent.com/96765406/154218881-3d278e9d-d5c4-4417-a074-5bef722c4270.png)

**Comment by hbarovertwo** [comment]
@cssddnnc9527 I just used https://github.com/NVlabs/stylegan2 ,  they have pretrained car networks. Used those to encode car images and interpolate between vectors for some good looking synthetic cars.
