### ISSUE TITLE
purpose of train_resnet

### ISSUE THREAD

**Issue by cristinasegalin** [pbaylies/stylegan-encoder#28]
Hi and thanks for your contribution.
What is the purpose of training or using resent/affnet model in encode_images if you already have the vgg perceptual model?

**Comment by MartiGrau** [comment]
Hi @cristinasegalin , you could check this video https://www.youtube.com/watch?v=dCKbRCUyop8  from 15:00 in advance in order to understand the ResNet or EfficientNet use.

**Comment by pbaylies** [comment]
Seconded, that's a great tutorial video! The resnet just serves to provide a good initial guess for the encoder.

**Comment by cristinasegalin** [comment]
Nice, I guessed that was the reason, wanted to confirm. thanks. I am curious to see how fast the optimization turns using this guess compared to now using it.
