### ISSUE TITLE
OSError: Unable to open file (file signature not found) loading the finetuned_resnet.h5

### ISSUE THREAD

**Issue by MartiGrau** [pbaylies/stylegan-encoder#33]
Hi @pbaylies ,

I'm trying to train the ResNET or efficientNET in order to generate an estimation of the latent vector of an input image of a bedroom.
In my case, I'm using the StyleGAN trained with LSUN Bedroom dataset at 256×256 to achieve a dataset of 10.000 synthesise bedroom images to train the ResNet.

**Training Step:**
Using your train_resnet.py code, the model is saved every 2 epochs in the following directory:
`save_path = 'data/finetuned_resnet.h5'`
`model.save(save_path)`

**Testing Step:**
When I try to load the above model in order to generate a latent vector for a specific bedroom image:
`load_resnet='data/finetuned_resnet.h5'`
`ff_model = load_model(args.load_resnet)`

**The following error occurs:**
`  File "/home/usuaris/imatge/mgrau/stylegan_env/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`

It seems like the h5py don't recognise my file/model..
I've searched and tried some solutions without success:
1) Trying to load you model and trying to load it. (Same error)
2) Change the filename and directory. (Same error)

There are someone with the same problem?
Could you provide me some solution to fix this bug?

Thank you,

**Comment by pbaylies** [comment]
Hi @MartiGrau 

I'm sorry, I haven't run into this bug; it looks like that's what h5py says when it has a file that's not found, or a corrupted file, which shouldn't be the issue here. Remember that the original StyleGAN code is not getting any newer, so it probably expects TF 1.4 or 1.5 and Keras 2.2.4. Good luck!
