### ISSUE TITLE
Why not use Dense layer during encoding?

### ISSUE THREAD

**Issue by mehameha998** [pbaylies/stylegan-encoder#34]
Hi @pbaylies, I'm consufed the reason you don't use Dense layer after Tree Connect, because generally speaking, we won't add ReLU/ELU after the last layer.

**Comment by pbaylies** [comment]
Hi @mehameha998 - I'm specifically avoiding dense layers here because of the number of weights involved -- (18*512)^2 is a lot of numbers!

**Comment by mehameha998** [comment]
However, the elu activate function will limit the scale of latent code.
