### ISSUE TITLE
How to calculate the proportion of each loss

### ISSUE THREAD

**Issue by Decalogue** [pbaylies/stylegan-encoder#35]
Hi!
This work is excellent! I want to know how to calculate the proportion of each loss(such as your default value: 0.4,1.5,100,100,1). 
Thank you so much!

**Comment by pbaylies** [comment]
Hi Decalogue,

Those numbers are used as scaling factors for the various parts of the loss function; unfortunately, during the course of training, the losses will all influence each other and change over time. They were obtained by trial and error; good luck!
