### ISSUE TITLE
Generator Error

### ISSUE THREAD

**Issue by mchello1986** [pbaylies/stylegan-encoder#38]
Thank you very much for sharing the good code.

I keep getting the following error while running the example in colab.
I'm almost there, and I would appreciate your help.

---------------------------------------------------------------------------
**ValueError                                Traceback (most recent call last)**
<ipython-input-8-0582b5d86c5d> in <module>()
     16     generator_network, discriminator_network, Gs_network = pickle.load(f)
     17 
---> 18 generator = Generator(Gs_network, batch_size=1, randomize_noise=False)
     19 
     20 model_res = 1024

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    866         tb = [x for x in tb if "tensorflow/python" not in x[0]][:5]
    867         raise ValueError("%s Originally defined at:\n\n%s" %
--> 868                          (err_msg, "".join(traceback.format_list(tb))))
    869       found_var = self._vars[name]
    870       if not shape.is_compatible_with(found_var.get_shape()):

**ValueError: Variable learnable_dlatents already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:**

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)

**Comment by pbaylies** [comment]
@mchello1986 make sure you have the right version of Tensorflow for StyleGAN - unfortunately, Google Colab is a moving target!
