### ISSUE TITLE
Request - Add support for StyleGanV2

### ISSUE THREAD

**Issue by ofirkris** [pbaylies/stylegan-encoder#39]
Hi, Would be great if you can make your encoder support the latest Stylegan version - Reference to Puzer StyleganV2 fork - https://github.com/rolux/stylegan2encoder

**Comment by pbaylies** [comment]
@ofirkris I've thought about this - this would be better done as a fork of StyleGAN2. Anyone would be welcome to do this, currently I'm taking a break from active development over the holidays.

**Comment by oneiroid** [comment]
Karras implemented projecting to latent space right there in the original repo yo. Don't think it can be improved any more. He's using tiled (1, 512) dlatent though, I suppose as a preemptive measure against censorship activists. Made a couple of changes to project to (18, 512) space: https://github.com/oneiroid/stylegan2

![image0001-step2000](https://user-images.githubusercontent.com/3052196/71293393-e8b0b380-237d-11ea-8c52-0c3b170095e8.png)
![image0001-target](https://user-images.githubusercontent.com/3052196/71293394-e9494a00-237d-11ea-9817-7936fe301c08.png)

**Comment by wduo** [comment]
@oneiroid Did you run `python align_images.py` before `python encode_images.py`?

**Comment by rolux** [comment]
> Karras implemented projecting to latent space right there in the original repo yo. Don't think it can be improved any more. He's using tiled (1, 512) dlatent though, I suppose as a preemptive measure against censorship activists. Made a couple of changes to project to (18, 512) space: https://github.com/oneiroid/stylegan2

@oneiroid: Uh, you're totally right!

![Ginevra de Benci_01](https://user-images.githubusercontent.com/152646/71528408-f61af000-28df-11ea-832c-e1af8e7d5fe9.png)

![Ginevra de Benci_01](https://user-images.githubusercontent.com/152646/71528415-00d58500-28e0-11ea-95d0-15e02dc2270d.png)

Optimization video: https://youtu.be/DqOXWb1fvHk

This looks pretty good to me!

**Comment by rolux** [comment]
In the meantime, I've done two things: ported this repo to StyleGAN2 ([link](https://github.com/robertluxemburg/stylegan2encoder)), at least up to the point where the tutorial notebook runs; and, in my own port of Puzer's encoder ([link](https://github.com/rolux/stylegan2encoder)), added a `project_images.py` equivalent to `encode_images.py`.

My impression is that there is a lot of cool stuff in here that would be great to have in StyleGAN2. On the other hand, from a "user" - as opposed to "researcher" - perspective, a two-line change to the projector, plus a bit of glue around it, seems kind of hard to beat.

**Comment by Jakorbie** [comment]
> Karras implemented projecting to latent space right there in the original repo yo. Don't think it can be improved any more. He's using tiled (1, 512) dlatent though, I suppose as a preemptive measure against censorship activists. Made a couple of changes to project to (18, 512) space: https://github.com/oneiroid/stylegan2
> 
> ![image0001-step2000](https://user-images.githubusercontent.com/3052196/71293393-e8b0b380-237d-11ea-8c52-0c3b170095e8.png)
> ![image0001-target](https://user-images.githubusercontent.com/3052196/71293394-e9494a00-237d-11ea-9817-7936fe301c08.png)

What do you mean "against censorship" ? I don't understand.
Why would anyone want to censor this?

**Comment by woctezuma** [comment]
> Karras implemented projecting to latent space right there in the original repo yo. Don't think it can be improved any more. He's using tiled (1, 512) dlatent though, I suppose as a preemptive measure against censorship activists. Made a couple of changes to project to (18, 512) space: https://github.com/oneiroid/stylegan2

Hello @oneiroid, would you mind explaining what you meant as "preemptive measure against censorship activists"? I am trying to understand this (18, 512) change (https://github.com/rolux/stylegan2encoder/issues/21), and so far, my understanding is that the visual fidelity is better but the semantic fidelity (for interpolation, etc.) is not. I assume that is the reason why Nvidia's implementation uses (1 ,512). I would be curious about your other explanation.

**Comment by oneiroid** [comment]
Hi @woctezuma, I positively wouldn't mind explaining :))
Using (1, 512) dlatents you will never get good projection for any face that was not present in the training dataset.
Using (18, 512) dlats you can project any face. And then you can apply facial attributes directions - emotions, age, gender.
Even celebrity faces! And them celebrities got their faces copyrighted and sold for good money. 
So there could've been deepfakes-style hysteria and calls to forbid everything starting from GANs down to internet and  propagation of light reflected off their precioussssssss privately owned faces. 
Karras and Nvidia do not need such sick activity around them. I hope I made myself clear. I'm a bit distressed recently by all the sick things happening, tried my best :)

**Comment by woctezuma** [comment]
Thank you for clarifying. It helps me in my understanding of this change!
