### ISSUE TITLE
W latent vector prediction model

### ISSUE THREAD

**Issue by mrgloom** [pbaylies/stylegan-encoder#4]
Is it true that model that predict W latent vector (i.e. `train_resnet.py`) can be only used as initial estimate of W latent vector in optimization process? i.e. it's not possible to directly use this model to predict W latent vector without optimization process(i.e. it looks like if it used like this it change person identity)?

**Comment by pbaylies** [comment]
That's true; if you train a feed forward network to predict latents for a long time, it will slowly improve, but the job here is to serve as a good initial estimate, not a final prediction. (an example of this is in the banner at the top of this repo)
