### ISSUE TITLE
learn directions  in latent space about facial attributes

### ISSUE THREAD

**Issue by LingQiu** [pbaylies/stylegan-encoder#44]
Hi, @pbaylies when using the Learn_direction_in_latent_space notebook for training the facial attributes of the age, the shape of the clf.coef_ is (72,9216).how to process? Here some results.
![QQ截图20191231100615](https://user-images.githubusercontent.com/20528352/71607553-42528280-2bb5-11ea-8007-8c02a66b3cf3.png)
what's more, can you give some suggestions to train the face pose?

**Comment by pbaylies** [comment]
Hi @LingQiu those notebooks are from the original encoder repo from @Puzer - he also provided a dataset of encodings and their classified attributes, that you can use to train directions. You should be able to step through the notebook, and this includes pitch, yaw and roll which can control face pose.
