### ISSUE TITLE
OSError: Google Drive quota exceeded

### ISSUE THREAD

**Issue by Zeltserj** [pbaylies/stylegan-encoder#46]
I'm trying to run `train_resnet.py` but I keep getting this:
 
`OSError: Google Drive quota exceededOSError: Google Drive quota exceeded` issue. 

I tried to work around it by downloading the file in the default URL and uploading it to my own personal Google Drive, and then I get this error:

`Downloading https://drive.google.com/open?id=1CeLTgZHwnwXG7rc0rXSxsf2uumBwRga6 ... done
Traceback (most recent call last):
  File "train_resnet.py", line 242, in <module>
    generator_network, discriminator_network, Gs_network = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '<'.`

Which I looked up and could not find anything useful. 
Any help on how to move forward and be able to train a resent / utilize the pretrained one?

**Comment by pbaylies** [comment]
Errors like that typically mean that you have a corrupted file. If you have no file present, then train_resnet.py will train a new one, but you might want to run it for a day or three.
