### ISSUE TITLE
StyleGAN2 support

### ISSUE THREAD

**Issue by eladrich** [pbaylies/stylegan-encoder#47]
Hi, 
Really like what you did here, I was wondering if you're planning to train a new ResNet model for StyleGAN2, or could guide me through the process, it would be interesting to see how it compares :)

**Comment by pbaylies** [comment]
I do also have a repo that supports StyleGAN 2 now, based on skyflynil's repo and a few others. The ResNet code is basically the same, though; you just need to run the train_resnet.py script for a few days :)

**Comment by eladrich** [comment]
Nice! Do you also happen to have a pretrained model there to save these few days? 🙃

**Comment by pbaylies** [comment]
I have one in my repo for the WikiArt model I trained, but not for the default NVIDIA models.
