### ISSUE TITLE
Render npy not matching the generated images

### ISSUE THREAD

**Issue by rlzhang** [pbaylies/stylegan-encoder#49]
@pbaylies , thanks for the awesome work. 
Do you have any ideas why the saved latent representations are not matching the generated images? I tried to regenerate images from your saved latent vectors, but the new generated images are different.

**Comment by rlzhang** [comment]
Here is my code to generate images:
def generate_images(Gs, latent):
    assert(latent.shape == (1, 18, 512))
    fmt = dict(func=tflib.convert_images_to_uint8, nchw_to_nhwc=True)
    synthesis_kwargs = dict(output_transform=fmt, truncation_psi=0.7, minibatch_size=1)
    images = Gs.components.synthesis.run(latent, randomize_noise=False, **synthesis_kwargs)
    return images

**Comment by sirius-ai** [comment]
I met the same issue, do you have solve?

**Comment by sirius-ai** [comment]
I found that it is cause by use face_mask.
