### ISSUE TITLE
Where is imutils is defined?

### ISSUE THREAD

**Issue by mrgloom** [pbaylies/stylegan-encoder#5]
Where is `imutils` is defined?
```
File "/data_large/stylegan/stylegan-encoder/encoder/perceptual_model.py", line 136, in generate_face_mask
    from imutils import face_utils
ModuleNotFoundError: No module named 'imutils'
```
https://github.com/pbaylies/stylegan-encoder/blob/master/encoder/perceptual_model.py#L136

**Comment by pbaylies** [comment]
It's [an external dependency](https://pypi.org/project/imutils/), you can install it with pip or whatnot.
