### ISSUE TITLE
Two bugs found

### ISSUE THREAD

**Issue by YotamNitzan** [pbaylies/stylegan-encoder#54]
First, hats off for the amazing repo !
Second, I've identified two bugs you'd might want to fix.

- Running with "--tile_dlatents=true" doesn't work for me. The shape of the dlatents seems wrong as it should be (batch_size, 1, 512) instead of (batch_size, 512). 

- After fixing this, I still wasn't able to run the code with lower StyleGAN resolutions (e.g with "--model_res=256").  The "create_variable_for_generator" function should get as input the correct "model_scale" instead of using default value 18.

These two bugs are very simple to resolve, I've fixed both locally and it works for me.
I'll be happy to contribute, please let me know if I should submit a PR.

**Comment by pbaylies** [comment]
Thanks, @YotamNitzan -- yes, a PR would be much appreciated!

**Comment by YotamNitzan** [comment]
Hi again @pbaylies,
Just reminding that I've created a PR, in case you missed it.
