### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Dimension'

### ISSUE THREAD

**Issue by Michi-123** [pbaylies/stylegan-encoder#55]
Running  
!python train_resnet.py --help 
on Google Colab, I got message
AttributeError: module 'tensorflow' has no attribute 'Dimension'

I don't know how to fix it.

**Comment by Weisheng97** [comment]
Try running the code below before running to make sure that TensorFlow 1.x selected. 1.15.2 

%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

**Comment by Michi-123** [comment]
Thanks!
