### ISSUE TITLE
Compatibility with pretrained stylegan2 model?

### ISSUE THREAD

**Issue by Mehrab-Tanjim** [pbaylies/stylegan-encoder#58]
If I give the model url for pretrained stylegan2 model, it throws an error, so I think the current repo is not yet compatible with stylegan2. Any plan to include that?

**Comment by ChengBinJin** [comment]
@Mehrab-Tanjim StyleGANv2 can work @pbaylies repository. You just need to revise several parts and include some files from the official repository.

**Comment by MichalZajac** [comment]
Hi @ChengBinJin,
Could you please be more specific? - Do you have some repository where you did those adaptations? 
I would like to take a look.
Thank you.

**Comment by ChengBinJin** [comment]
@MichalZajac 
Put custom_ops.py from StyleGANv2 under the folder of tflib:
![image](https://user-images.githubusercontent.com/37034031/97649503-75de9180-1a92-11eb-9ea5-53a9c6c4bf1c.png)

Revise network.py 279 line as the following:
![image](https://user-images.githubusercontent.com/37034031/97649461-5cd5e080-1a92-11eb-8a41-25f45684eacf.png)

**Comment by ChengBinJin** [comment]
@MichalZajac 
I revised it several months ago, some details I forgot it. But Pbaylies inversion can work for StyleGANv2 actually.

**Comment by MichalZajac** [comment]
@ChengBinJin thank you
you saved my day

**Comment by datduong** [comment]
Has anyone try this trick to make this github work with stylegan2-ada? Thanks.

**Comment by pbaylies** [comment]
@datduong https://github.com/pbaylies/stylegan2-ada
