### ISSUE TITLE
train encoder directly

### ISSUE THREAD

**Issue by Nickzhangkaiyu** [pbaylies/stylegan-encoder#59]
That's so cool! And I have some qustions. Why not train an encoder which outputs the latent code directly, instead of optimizing the latent variables iteratively  which may be time-consuming.

**Comment by pbaylies** [comment]
Hi Nick! There is code for that here as well, you can fine-tune a ResNet to predict latent codes, for example. For a more recent and very cool looking approach, check out idinvert: https://github.com/genforce/idinvert
