### ISSUE TITLE
Why can't we find the vector Z and have to use W ?

### ISSUE THREAD

**Issue by datduong** [pbaylies/stylegan-encoder#64]
Does anyone know why we can't directly optimize for Z which is the 1st input to StyleGAN? Why do we have to optimize for W which is an intermediate input? 

Thanks.

**Comment by pbaylies** [comment]
Historically optimizing for W directly tends to work better, because the StyleGAN mapping network disentangles the image features into latents that are semantically meaningful, whereas the Z input is just a gaussian distribution.

**Comment by datduong** [comment]
Thanks.
