### ISSUE TITLE
runing StyleGAN_Encoder  sehape error 

### ISSUE THREAD

**Issue by EricShui** [pbaylies/stylegan-encoder#65]
runing this:
!python encode_images.py --batch_size=4 --output_video=True --load_resnet='data/finetuned_resnet.h5' --lr=0.01 -decay_rate=0.8 --iterations=200 --use_l1_penalty=0.3 aligned_images/ generated_images/ latent_representations/

error is :
Traceback (most recent call last):
  File "encode_images.py", line 241, in <module>
    main()
  File "encode_images.py", line 230, in main
    img_array = mask*np.array(img_array) + (1.0-mask)*np.array(orig_img)
ValueError: operands could not be broadcast together with shapes (1048,1048,1) (1024,1024,3)

encode_images.py   line  228-231 is:

                mask = np.array(imask)/255
                mask = np.expand_dims(mask,axis=-1)
                img_array = mask*np.array(img_array) + (1.0-mask)*np.array(orig_img)
                img_array = img_array.astype(np.uint8)

**Comment by mumumu99** [comment]
Have you solved it?

**Comment by pbaylies** [comment]
Sure - try using an image as input that is 1024x1024?
