### ISSUE TITLE
identity and age

### ISSUE THREAD

**Issue by ak9250** [pbaylies/stylegan-encoder#7]
when using the Learn_direction_in_latent_space notebook for a specific facial attribute like glasses, the identity and age seem to change in the trained vector outputs

**Comment by pbaylies** [comment]
@ak9250 this isn't really surprising if you think about it -- wearing glasses is statistically correlated in the data with age, as people get older they tend to need glasses. You could try to solve this by first sampling the data to ensure an even distribution across the classes you care about for a given attribute.
