### ISSUE TITLE
'latent_training_data' is no longer available

### ISSUE THREAD

**Issue by dongyunkim-arch** [pbaylies/stylegan-encoder#70]
Hello, I am trying to analyze feature vector and follow Learn_direction_in_latent_space notebook. However, the link in the notebook for latent_training_data is not available. 

LATENT_TRAINING_DATA = 'https://drive.google.com/uc?id=1xMM3AFq0r014IIhBLiMCjKJJvbhLUQ9t'

Is there any way to have access to this data?

Thanks!

**Comment by pbaylies** [comment]
I just happened to have this cached, I've put a copy up for download here: https://archive.org/details/latent_training_data.pkl
