### ISSUE TITLE
learning directions

### ISSUE THREAD

**Issue by ak9250** [pbaylies/stylegan-encoder#9]
how would you get something like 'emotion' 'happiness' for the linear model?
y_emotion_data = np.array([x['faceAttributes']['emotion']['happiness'] for x in labels_data])?

**Comment by ak9250** [comment]
solved it using this

from sklearn.linear_model import SGDRegressor
sgds = SGDRegressor()
sld = sgds.fit(x_test, y_test)
results = sld.coef_.reshape((18, 512))

**Comment by pbaylies** [comment]
@ak9250 the notebooks in the repo left over from @Puzer do a decent job of outlining how to do this, as well; glad you figured it out!
